/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ApiPublicGoogleOauthCallbackRouteImport } from './routes/api/public/google-oauth-callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleOauthCallbackRoute =
  ApiPublicGoogleOauthCallbackRouteImport.update({
    id: '/api/public/google-oauth-callback',
    path: '/api/public/google-oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite/$token': typeof InviteTokenRoute
  '/api/public/google-oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite/$token': typeof InviteTokenRoute
  '/api/public/google-oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invite/$token': typeof InviteTokenRoute
  '/api/public/google-oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/invite/$token' | '/api/public/google-oauth-callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/invite/$token' | '/api/public/google-oauth-callback'
  id: '__root__' | '/' | '/invite/$token' | '/api/public/google-oauth-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicGoogleOauthCallbackRoute: typeof ApiPublicGoogleOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-oauth-callback': {
      id: '/api/public/google-oauth-callback'
      path: '/api/public/google-oauth-callback'
      fullPath: '/api/public/google-oauth-callback'
      preLoaderRoute: typeof ApiPublicGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicGoogleOauthCallbackRoute: ApiPublicGoogleOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
